/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.painel.frames.paineis;

/**
 *
 * @author Tiago
 */
public final class banheira extends javax.swing.JPanel {

    private static final long serialVersionUID = 5062915923269603288L;

    /**
     * Creates new form fornoMicroondas
     *
     * @param rotulo
     */
    public banheira(String rotulo) {
        initComponents();
        initBanheira(rotulo);
    }

    private void initBanheira(String rotulo) {
        lbRotulo.setText(rotulo);
        if (!rotulo.equals("Banheira 1")) {
            lbMicroPctSet1.setText("");
            lbMicroPctInd1.setText("");
        } else {
            jLabel32.setVisible(false);
            jLabel33.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRotulo = new javax.swing.JLabel();
        lbMicroPctSet1 = new javax.swing.JLabel();
        lbMicroPctInd1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbBanheirareseRvatorioSet = new javax.swing.JLabel();
        lbBanheirareseRvatorioInd = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbBanheira1BombaTanqueON = new javax.swing.JLabel();
        lbBanheira1BombaTanqueOf = new javax.swing.JLabel();
        lbBanheira1BombaChillerON = new javax.swing.JLabel();
        lbBanheira1BombaChillerOF = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRotulo.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        lbRotulo.setForeground(new java.awt.Color(255, 255, 255));
        lbRotulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRotulo.setPreferredSize(new java.awt.Dimension(170, 40));
        add(lbRotulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 120, 170, 40));

        lbMicroPctSet1.setForeground(new java.awt.Color(255, 255, 153));
        lbMicroPctSet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMicroPctSet1.setText("Null");
        lbMicroPctSet1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbMicroPctSet1.setPreferredSize(new java.awt.Dimension(60, 25));
        add(lbMicroPctSet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, -1, -1));

        lbMicroPctInd1.setForeground(new java.awt.Color(0, 255, 255));
        lbMicroPctInd1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMicroPctInd1.setText("Null");
        lbMicroPctInd1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbMicroPctInd1.setPreferredSize(new java.awt.Dimension(60, 25));
        add(lbMicroPctInd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 42, -1, -1));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Cº");
        jLabel33.setPreferredSize(new java.awt.Dimension(12, 20));
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 18, 20, 20));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Cº");
        jLabel32.setPreferredSize(new java.awt.Dimension(12, 20));
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 43, 20, -1));

        lbBanheirareseRvatorioSet.setForeground(new java.awt.Color(255, 255, 153));
        lbBanheirareseRvatorioSet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBanheirareseRvatorioSet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbBanheirareseRvatorioSet.setPreferredSize(new java.awt.Dimension(60, 25));
        add(lbBanheirareseRvatorioSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 15, -1, -1));

        lbBanheirareseRvatorioInd.setForeground(new java.awt.Color(0, 255, 255));
        lbBanheirareseRvatorioInd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBanheirareseRvatorioInd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbBanheirareseRvatorioInd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 42, 60, 25));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Cº");
        jLabel34.setPreferredSize(new java.awt.Dimension(12, 20));
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 18, 20, 20));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Cº");
        jLabel35.setPreferredSize(new java.awt.Dimension(12, 20));
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 43, 20, -1));

        lbBanheira1BombaTanqueON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/painel/img/button_blank_green_14986.png"))); // NOI18N
        add(lbBanheira1BombaTanqueON, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        lbBanheira1BombaTanqueOf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/painel/img/button_blank_red_14987.png"))); // NOI18N
        add(lbBanheira1BombaTanqueOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        lbBanheira1BombaChillerON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/painel/img/button_blank_green_14986.png"))); // NOI18N
        add(lbBanheira1BombaChillerON, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        lbBanheira1BombaChillerOF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/painel/img/button_blank_red_14987.png"))); // NOI18N
        add(lbBanheira1BombaChillerOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/painel/img/novos/banheira1.gif"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 270));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel lbBanheira1BombaChillerOF;
    private javax.swing.JLabel lbBanheira1BombaChillerON;
    private javax.swing.JLabel lbBanheira1BombaTanqueON;
    private javax.swing.JLabel lbBanheira1BombaTanqueOf;
    private javax.swing.JLabel lbBanheirareseRvatorioInd;
    private javax.swing.JLabel lbBanheirareseRvatorioSet;
    private javax.swing.JLabel lbMicroPctInd1;
    private javax.swing.JLabel lbMicroPctSet1;
    private javax.swing.JLabel lbRotulo;
    // End of variables declaration//GEN-END:variables
}
