/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.painel.frames.paineis;

/**
 *
 * @author Tiago
 */
public final class hotAir extends javax.swing.JPanel {

    private static final long serialVersionUID = 5236847333013637559L;

    /**
     * Creates new form fornoMicroondas
     * @param rotulo
     */
    public hotAir(String rotulo) {
        initComponents();
        initHotAir(rotulo);
    }

    private void initHotAir(String rotulo){
        lbRotulo.setText(rotulo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRotulo = new javax.swing.JLabel();
        lbVulc1QueimadorSet = new javax.swing.JLabel();
        lbVulc1QueimadorInd = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbVulc1Queimador2Set = new javax.swing.JLabel();
        lbVulc1Queimador2Ind = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbVulc1EsteiraSet = new javax.swing.JLabel();
        lbVulc1EsteiraInd = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRotulo.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        lbRotulo.setForeground(new java.awt.Color(255, 255, 255));
        lbRotulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRotulo.setPreferredSize(new java.awt.Dimension(170, 40));
        add(lbRotulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 115, 170, 40));

        lbVulc1QueimadorSet.setForeground(new java.awt.Color(255, 255, 153));
        lbVulc1QueimadorSet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVulc1QueimadorSet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbVulc1QueimadorSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 12, 60, 25));

        lbVulc1QueimadorInd.setForeground(new java.awt.Color(0, 255, 255));
        lbVulc1QueimadorInd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVulc1QueimadorInd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbVulc1QueimadorInd, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 40, 60, 25));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Cº");
        jLabel24.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 12, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Cº");
        jLabel25.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        lbVulc1Queimador2Set.setForeground(new java.awt.Color(255, 255, 153));
        lbVulc1Queimador2Set.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVulc1Queimador2Set.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbVulc1Queimador2Set, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 12, 60, 25));

        lbVulc1Queimador2Ind.setForeground(new java.awt.Color(0, 255, 255));
        lbVulc1Queimador2Ind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVulc1Queimador2Ind.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbVulc1Queimador2Ind, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 40, 60, 25));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Cº");
        jLabel27.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 12, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Cº");
        jLabel26.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        lbVulc1EsteiraSet.setForeground(new java.awt.Color(255, 255, 153));
        lbVulc1EsteiraSet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVulc1EsteiraSet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbVulc1EsteiraSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 205, 60, 25));

        lbVulc1EsteiraInd.setForeground(new java.awt.Color(0, 255, 255));
        lbVulc1EsteiraInd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVulc1EsteiraInd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbVulc1EsteiraInd, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 233, 60, 25));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("m/min");
        jLabel29.setPreferredSize(new java.awt.Dimension(35, 25));
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 205, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("m/min");
        jLabel28.setPreferredSize(new java.awt.Dimension(35, 25));
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 233, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/painel/img/novos/hotAir.gif"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 270));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel lbRotulo;
    private javax.swing.JLabel lbVulc1EsteiraInd;
    private javax.swing.JLabel lbVulc1EsteiraSet;
    private javax.swing.JLabel lbVulc1Queimador2Ind;
    private javax.swing.JLabel lbVulc1Queimador2Set;
    private javax.swing.JLabel lbVulc1QueimadorInd;
    private javax.swing.JLabel lbVulc1QueimadorSet;
    // End of variables declaration//GEN-END:variables
}
