/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.painel.frames.paineis;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Tiago
 */
public final class L01ATBOverView extends javax.swing.JFrame {

    private static final long serialVersionUID = 1103014303075211021L;

    /**
     * Creates new form L01ATBOverView
     */
    public L01ATBOverView() {
        initComponents();
        //configGG();
        configSmall();
    }

    public void configGG() {
        //linha 1
        jPanel1.add(new labelControle(), new AbsoluteConstraints(640, 0));
        jPanel1.add(new extrusoraMonitoramento(), new AbsoluteConstraints(66, 115));
        jPanel1.add(new fornoMicroondas(), new AbsoluteConstraints(280, 185));
        jPanel1.add(new hotAir("HotAir 1"), new AbsoluteConstraints(660, 185));
        jPanel1.add(new hotAir("HotAir 2"), new AbsoluteConstraints(957, 185));
        jPanel1.add(new banheira("Banheira 1"), new AbsoluteConstraints(1254, 180));
        jPanel1.add(new puller1(), new AbsoluteConstraints(1513, 180));
        jPanel1.add(new plasma(), new AbsoluteConstraints(1643, 178));
        //linha 2
        jPanel1.add(new pintura(), new AbsoluteConstraints(20, 647));
        jPanel1.add(new infraRed(), new AbsoluteConstraints(285, 647));
        jPanel1.add(new banheira("Banheira 2"), new AbsoluteConstraints(700, 654));
        jPanel1.add(new banheira("Banheira 3"), new AbsoluteConstraints(970, 654));
        jPanel1.add(new puller2(), new AbsoluteConstraints(1232, 647));
        jPanel1.add(new furadeira(), new AbsoluteConstraints(1364, 655));
        jPanel1.add(new puller3(), new AbsoluteConstraints(1494, 655));
        jPanel1.add(new cortadeira(), new AbsoluteConstraints(1621, 655));
        jPanel1.add(new JLabel(new ImageIcon(getClass().getResource("/br/com/painel/img/novos/backgroundGG.gif"))), new AbsoluteConstraints(0, 0));
    }

    public void configSmall() {
        //linha 1
        jPanel1.add(new labelControle(), new AbsoluteConstraints(355, 0));
        jPanel1.add(new extrusoraMonitoramento(), new AbsoluteConstraints(53, 19));
        jPanel1.add(new fornoMicroondas(), new AbsoluteConstraints(280, 90));
        jPanel1.add(new hotAir("HotAir 1"), new AbsoluteConstraints(660, 90));
        jPanel1.add(new hotAir("HotAir 2"), new AbsoluteConstraints(957, 90));
        //linha 2
        jPanel1.add(new banheira("Banheira 1"), new AbsoluteConstraints(28, 432));
        jPanel1.add(new puller1(), new AbsoluteConstraints(296, 432));
        jPanel1.add(new plasma(), new AbsoluteConstraints(434, 432));
        jPanel1.add(new pintura(), new AbsoluteConstraints(564, 432));
        jPanel1.add(new infraRed(), new AbsoluteConstraints(835, 432));
        //linha 3
        jPanel1.add(new banheira("Banheira 2"), new AbsoluteConstraints(28, 708));
        jPanel1.add(new banheira("Banheira 3"), new AbsoluteConstraints(292, 708));
        jPanel1.add(new puller2(), new AbsoluteConstraints(568, 701));
        jPanel1.add(new furadeira(), new AbsoluteConstraints(700, 708));
        jPanel1.add(new puller3(), new AbsoluteConstraints(830, 708));
        jPanel1.add(new cortadeira(), new AbsoluteConstraints(960, 707));
        jPanel1.add(new JLabel(new ImageIcon(getClass().getResource("/br/com/painel/img/novos/background.gif"))), new AbsoluteConstraints(0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L01ATBOverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L01ATBOverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L01ATBOverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L01ATBOverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new L01ATBOverView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
