/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.painel.status;

import br.com.painel.util.Auxiliar;
import br.com.painel.util.EstiloTablaHeader;
import br.com.painel.util.EstiloTablaRenderer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rsouza10
 */
public class L09Alarmes extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel(null, new String[]{"Data", "Hora", "Nome Alarme", "Valor", "Mensagem"}) {
        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }

    };

    public L09Alarmes() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        PreencherTabela();
        tbAlarmesAtivos.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        tbAlarmesAtivos.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlarmesAtivos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbAlarmesAtivos.setAutoCreateRowSorter(true);
        tbAlarmesAtivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbAlarmesAtivos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, 920, 854));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("09");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 7, 50, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/painel/img/Alarme09.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 965));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void PreencherTabela() {
        try {
            modelo.setNumRows(0);
            Class.forName(Auxiliar.AcessoBanco.getDriver());
            Connection con = DriverManager.getConnection(Auxiliar.AcessoBanco.getUrl(), Auxiliar.AcessoBanco.getUser(), Auxiliar.AcessoBanco.getPass());
            String query1 = "Select E3TimeStamp,AlarmSourceName,CurrentValue,Message  from AlarmesL09 order BY E3TimeStamp DESC";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);

            while (rs.next()) {

                modelo.addRow(new Object[]{rs.getDate("E3TimeStamp"), rs.getTime("E3TimeStamp"), rs.getString("AlarmSourceName"), rs.getFloat("CurrentValue"), rs.getString("Message")});
            }

            modelo.isCellEditable(modelo.getColumnCount(), modelo.getRowCount());
            tbAlarmesAtivos.setModel(modelo);
            tbAlarmesAtivos.getColumnModel().getColumn(0).setMinWidth(90);
            tbAlarmesAtivos.getColumnModel().getColumn(0).setMaxWidth(90);
            tbAlarmesAtivos.getColumnModel().getColumn(1).setMinWidth(90);
            tbAlarmesAtivos.getColumnModel().getColumn(1).setMaxWidth(90);
            tbAlarmesAtivos.getColumnModel().getColumn(2).setMinWidth(250);
            tbAlarmesAtivos.getColumnModel().getColumn(2).setMaxWidth(250);
            tbAlarmesAtivos.getColumnModel().getColumn(3).setMinWidth(90);
            tbAlarmesAtivos.getColumnModel().getColumn(3).setMaxWidth(90);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L09Alarmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L09Alarmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L09Alarmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L09Alarmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new L09Alarmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbAlarmesAtivos;
    // End of variables declaration//GEN-END:variables
}
